spring.servlet.multipart:
  max-file-size: 100MB
  max-request-size: 100MB

# Firebase stuff
firebase:
  database.url: https://timelapse-server.firebaseio.com
  storage.bucket: timelapse-server.appspot.com
